version: '3'

networks:
  bibbox-default-network:
    external: true
services:
  bibbox-molgenis:
    container_name: bibbox-molgenis
    depends_on:
    - bibbox-molgenis-postgres
    environment:
    - molgenis.home=/home/molgenis
    - opencpu.uri.host=opencpu
    - elasticsearch.transport.addresses=elasticsearch:9300
    - db_uri=jdbc:postgresql://postgres/molgenis
    - db_user=molgenis
    - db_password=molgenis
    - admin.password=admin
    - MINIO_BUCKET_NAME=molgenis
    - MINIO_ENDPOINT=http://minio:9000
    - MINIO_ACCESS_KEY=molgenis
    - MINIO_SECRET_KEY=molgenis
    - MOLGENIS_MAX_FILE_MB=150
    - CATALINA_OPTS=-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
    image: molgenis/molgenis-app:8.7.2
    links:
    - bibbox-molgenis-postgres:postgres
    - bibbox-molgenis-minio:minio
    - bibbox-molgenis-elasticsearch:elasticsearch
    - bibbox-molgenis-opencpu:opencpu
    networks:
    - bibbox-default-network
    restart: unless-stopped
    volumes:
    - ./data/home/molgenis:/home/molgenis
  bibbox-molgenis-elasticsearch:
    container_name: bibbox-molgenis-elasticsearch
    environment:
    - cluster.name=molgenis
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    - discovery.type=single-node
    image: molgenis/molgenis-elasticsearch:1.0.0
    networks:
    - bibbox-default-network
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - ./data/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
  bibbox-molgenis-filebeat:
    container_name: bibbox-molgenis-filebeat
    depends_on:
    - bibbox-molgenis-elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    image: docker.elastic.co/beats/filebeat-oss:7.9.3
    networks:
    - bibbox-default-network
    profiles:
    - audit
    volumes:
    - ./data/usr/share/filebeat/input/:/usr/share/filebeat/input/
    - ./data/usr/share/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  bibbox-molgenis-frontend:
    container_name: bibbox-molgenis-frontend
    depends_on:
    - bibbox-molgenis
    image: molgenis/molgenis-frontend:8.7.2
    links:
    - bibbox-molgenis:molgenis
    networks:
    - bibbox-default-network
    ports:
      - "80:80"
    volumes:
    - ./data/backend.conf:/etc/nginx/proxy.d/backend.conf
  bibbox-molgenis-kibana:
    container_name: bibbox-molgenis-kibana
    image: docker.elastic.co/kibana/kibana:5.5.3
    networks:
    - bibbox-default-network
    profiles:
    - audit
  bibbox-molgenis-kibana-dashboard:
    command:
    - /bin/sh
    - -c
    - /root/dashboard/import.sh
    container_name: bibbox-molgenis-kibana-dashboard
    environment:
      DASHBOARD_FILE: https://raw.githubusercontent.com/molgenis/molgenis/master/.kibana/dashboard.json
    image: docker.elastic.co/kibana/kibana:5.5.3
    networks:
    - bibbox-default-network
    profiles:
    - audit
    user: 0:0
    volumes:
    - ./data:/root/dashboard:ro
  bibbox-molgenis-minio:
    command: server /data
    container_name: bibbox-molgenis-minio
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    image: minio/minio:RELEASE.2019-03-20T22-38-47Z
    networks:
    - bibbox-default-network
    volumes:
    - /data/minio/data:/data
  bibbox-molgenis-opencpu:
    container_name: bibbox-molgenis-fair-opencpu
    image: molgenis/opencpu:opencpu-release-2019-03-20_12-07-11
    networks:
    - bibbox-default-network
  bibbox-molgenis-postgres:
    command: -c 'shared_buffers=256MB' -c 'max_locks_per_transaction=1024'
    container_name: bibbox-molgenis-postgres
    environment:
    - POSTGRES_USER=molgenis
    - POSTGRES_PASSWORD=molgenis
    - POSTGRES_DB=molgenis
    image: postgres:11-alpine
    networks:
    - bibbox-default-network
    volumes:
    - ./data/var/lib/postgresql/data:/var/lib/postgresql/data

  # fdp containers
  bibbox-jupyter-fdp:
    image: jupyter/datascience-notebook:notebook-6.4.11
    container_name:  bibbox-molgenis-fair-jupyter
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - JUPYTER_TOKEN=FDP
    ports:
        - "8888:8888"
    volumes:
        - ./data/jupyter/home/jovyan/work:/home/jovyan/work

  bibbox-fdp:
    image: fairdata/fairdatapoint:1.13.1
    container_name:  bibbox-molgenis-fair-fdp
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "8080:80"
    volumes:
      - ./data/application.yml:/fdp/application.yml:ro
    links:
      - bibbox-blazegraph:blazegraph
      - bibbox-mongo:mongo
    environment:
      - CLIENTURL=http://localhost:8088
#    depends_on:
#      - virtuoso
#    environment:
#      - FDP_HOST=0.0.0.0
#      - FDP_PORT=8888
#    healthcheck:
#        test: curl --silent --fail http://0.0.0.0:$${FDP_PORT} || exit 1
#        interval: 5s
#    links:
#      - virtuoso:db

  bibbox-fdp-client:
    image: fairdata/fairdatapoint-client:1.13.0
    container_name:  bibbox-molgenis-fair-fdp-client
    ports:
      - 8088:80
    environment:
      - FDP_HOST=fdp
    links:
      - bibbox-fdp:fdp
    networks:
      - bibbox-default-network

  bibbox-mongo:
    image: mongo:4.0.12
    container_name:  bibbox-molgenis-fair-fdp-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/data:/data/db
    networks:
      - bibbox-default-network

  bibbox-blazegraph:
    image: metaphacts/blazegraph-basic:2.2.0-20160908.003514-6
    container_name:  bibbox-molgenis-fair-fdp-blazegraph
    ports:
      - 8081:8080
    volumes:
      - ./data/blazegraph:/blazegraph-data
    networks:
      - bibbox-default-network

